### ISSUE TITLE
Add missing config setting

### ISSUE THREAD

**Issue by ksearight** [NOAA-GSL/VxMETplusAMI#21]
Add “OMP_NUM_THREADS = 1” to the config section of defaults.conf

**Comment by ksearight** [comment]
Also:  I had to add the dateutil package to the AMI: `ami-0e65f9fc5ed1f8244`  with the name: `metplus-centos7-aws-1647956263`.  I used the command: `conda install -c anaconda python-dateutil`

**Comment by ian-noaa** [comment]
Sounds good. Thanks Keith! The `dateutil` package was addressed in #19 so I'll just focus on the new env variable here.

**Comment by ian-noaa** [comment]
It appears the `OMP_NUM_THREADS=1` was added for 4.1.0 in https://github.com/dtcenter/METplus/pull/1338 so adding it to the `defaults.conf` we supply should be all we need to do.

**Comment by ian-noaa** [comment]
@ksearight - it appears that the conda environment wasn't initialized properly which was why you had to install dateutil. I fixed this in commit f9a88ee in the associated PR.
